### ISSUE TITLE
Mirador plugins not displayed

### ISSUE THREAD

**Issue by sceccolini** [dbmdz/mirador-plugins#5]
Hello,

some of the plugins downloaded from here are workin fine; some others they are not working.
As example, as per instructions of the physical rules plugin we've added the phisycalRuls.js reference atfer loading Mirador, then we added the physicalRuler tag along with its metadata; however, the rules is failing to be displayed in the corresponding Mirador instance. Are we missing something other than modifying the container?

Thanks
Simone

**Comment by morpheus-87** [comment]
Hello @sceccolini,

could you please provide the manifest you are using? Maybe there's something missing in it.

Do you also have problems with the rest of the plugins?

**Comment by sceccolini** [comment]
Hello @morpheus-87,

the shareButtons and keyboardNavigator are working fine, while the phisicalRuler, the manifestButton and the viewUrl are not working. As manifests noone is working, either mine or the ones available in the standard Mirador build.

Thanks
Simone

**Comment by morpheus-87** [comment]
Hello @sceccolini,

could you please try with this manifest: https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb00113391/manifest ? Do you still have problems?

For the physical ruler plugin to work, you need to have a physical dimensions service defined on the canvas, see [here](http://iiif.io/api/annex/services/#physical-dimensions).

**Comment by sceccolini** [comment]
Hello @morpheus-87,

with your manifest it works fine. i guess I used the wrong manifests.

Thank you very much
Simone

**Comment by morpheus-87** [comment]
Hello @sceccolini,

could you please provide your manifest? It would be useful to test with it, if there are errors in the plugin.

Many thanks in advance for your help.

**Comment by morpheus-87** [comment]
Hello @sceccolini,

could you please provide your manifest? It would be useful to test with it, if there are errors in the plugin.

Many thanks in advance for your help.
