### ISSUE TITLE
Download plugin disappears if more than one Mirador-Windows displayed

### ISSUE THREAD

**Issue by datazuul** [dbmdz/mirador-plugins#6]
Wenn man über Ihr IIIF-Shelf ein Fenster öffnet, erscheint dort auch (am linken Ende der Symbolleiste oben rechts im Bild) die sehr komfortable Download-Funktion, die ja meines Wissens von Ihnen entwickelt wurde. Wenn man jedoch daneben noch ein zweites Fenster öffnet, verschwindet diese Funktion in allen Fenstern und kommt auch nicht wieder, wenn das zweite Fenster wieder geschlossen wird. (Wenn man das Dokument im Hauptfenster durch ein anderes Dokument der BSB ersetzt, bleibt die Downloadfunktion offenbar erhalten, jedoch nicht, wenn hier ein fremdes Dokument eingesetzt wird - gibt es da Downloadsperren in  Manifesten mancher Institutionen?).

**Comment by morpheus-87** [comment]
Is fixed with release 1.0.1.
